import {
  AlertTriangle,
  ArrowLeft,
  ArrowUpRight,
  Bell,
  Briefcase,
  Calendar,
  CalendarCheck,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Crown,
  DollarSign,
  Flame,
  Frown,
  Globe,
  Heart,
  Home,
  Info,
  LayoutGrid,
  Lock,
  MapPin,
  MessageCircle,
  MessageSquare,
  Moon,
  Pencil,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Smile,
  Sofa,
  Sparkles,
  Star,
  TrendingUp,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react'

// Реестр иконок (kebab-name → lucide-компонент). Расширяем по мере надобности —
// именованные импорты tree-shake'атся, лишнего в бандл не попадает.
export const iconRegistry = {
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  briefcase: Briefcase,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  crown: Crown,
  'dollar-sign': DollarSign,
  flame: Flame,
  frown: Frown,
  globe: Globe,
  heart: Heart,
  home: Home,
  info: Info,
  'layout-grid': LayoutGrid,
  lock: Lock,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  moon: Moon,
  pencil: Pencil,
  'rotate-ccw': RotateCcw,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  smile: Smile,
  sofa: Sofa,
  sparkles: Sparkles,
  star: Star,
  'trending-up': TrendingUp,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
}

export type IconName = keyof typeof iconRegistry
